# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-17 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Longinus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='config_redis_command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(blank=True, max_length=30, verbose_name='命令')),
                ('status', models.IntegerField(blank=True, verbose_name='状态: 1.支持/0.不支持')),
            ],
        ),
    ]
